### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by mdmaarschalk**
Small corrections and change the order of steps for enabling Data Flow Debug, you need to add a data flow activity before you can enable debug.

### CODE REVIEW

**Comment by mdmaarschalk** [comment]
Corrections added during Data & AI Bootcamp

**Comment by mdmaarschalk** [comment]
@djpmsft : Hi, can you please review?

**Comment by djpmsft** [comment]
@mdmaarschalk First off thanks for taking a look at this! Awesome to see community support. 

Unfortunately,  I don't think ' Note: You can only enable Data Flow Debug when you have a Data Flow activity in your pipeline.' Is the slider not available for you on factory start up? If so, this is an ADF bug :)

**Comment by mdmaarschalk** [comment]
You're right, I created a new Data Factory, and it shows me the debug button right from the start. I suspect a browser issue. Thanks

**Pull request closed without merging**
